import pandas as pd

df = pd.read_csv("data/municipios_renda.csv", sep=",", encoding="utf-8")
print("Formato (linhas, colunas):", df.shape)
print()
print("Colunas e tipos de dado:")
print(df.dtypes)
print()
print("Primeiras 5 linhas:")
print(df.head())
print()
print("Valores nulos por coluna:")
print(df.isnull().sum())
print()
print("Linhas duplicadas:", df.duplicated().sum())
print()
print("Estatísticas rápidas (só pra conferência, NÃO é o que vai na app):")
print(df[["populacao", "renda_media_mensal", "pib_anual_mil_reais", "pib_per_capita_reais"]].describe())
print()
print("Quantos municípios por região:")
print(df["regiao"].value_counts())